### ISSUE TITLE
I cannot get the interface to complete and make files

### ISSUE THREAD

**Issue by cchaswell** [HALFpipe/HALFpipe#105]
**What happened?**
I downloaded halfpipe:latest last week and have not been able to get the interface to complete. It runs, but then sits for 12+ hours and I finally have to end it. 
<img width="638" alt="Screen Shot 2021-04-27 at 9 32 35 AM" src="https://user-images.githubusercontent.com/40609098/116250670-eca3d100-a73b-11eb-9e7b-66d4ed889443.png">

**Is there an error message?**
No. It does not do anything but hang. No err.txt gets created. No execgraph file or submit_slurm is created either. 

**What is the exact command that you used to run `Halfpipe`?**
Please copy it here in full.

**Which settings did you use?**
 This is what the log.txt shows.
[2021-04-26 21:12:01,0434] [halfpipe        ] [INFO     ] Halfpipe version 1.0.0b6+40.g8199f57
[2021-04-26 21:12:01,0438] [halfpipe        ] [IMPORTANT] Option "--verbose" was not specified. Will not print detailed logs to the terminal. 
ââDetailed logs information will only be available in the "log.txt" file in the working directory. 
[2021-04-26 21:12:01,0439] [halfpipe        ] [INFO     ] Stage: spec-ui
[2021-04-26 21:30:54,0201] [halfpipe        ] [INFO     ] Stage: workflow
[2021-04-26 21:30:54,0202] [halfpipe        ] [INFO     ] config.nipype.omp_nthreads=2 (from --use-cluster)
[2021-04-26 21:30:58,0058] [halfpipe        ] [INFO     ] Loading spec file /ext/mnt/BIACnfs/duhsnas-pri.dhe.duke.edu/morey_biac/Lab/Duke_data/spec.json
[2021-04-26 21:30:58,0099] [halfpipe        ] [INFO     ] Initializing file database
[2021-04-26 21:30:58,0671] [halfpipe        ] [INFO     ] Initializing new workflow d38ff754
[2021-04-26 21:50:07,0027] [nipype.workflow ] [IMPORTANT] 
â     Running fMRIPREP version 20.2.1+halfpipe.2:
â       * BIDS dataset path: /ext/mnt/BIACnfs/duhsnas-pri.dhe.duke.edu/morey_biac/Lab/Duke_data/rawdata.
â       * Participant list: ['1258', '12947', '12966', '13116', '13265', '13297', '13313', '13354', '1341', '13585', '13831', '13864', '13877', '14010', '14157', '14254', '15125', '1515', '15464', '15586', '15780', '15786', '15871', '15933', '16206', '16691', '16736', '16769', '16778', '16812', '16834', '16907', '16959', '17320', '17574', '17581', '17596', '17615', '17649', '17666', '17672', '1786', '18298', '18377', '18405', '18409', '18464', '18493', '18515', '1853', '18540', '18595', '18603', '18615', '18652', '18678', '18689', '18754', '18792', '18826', '18836', '18867', '18898', '18912', '18925', '19027', '19038', '19079', '19118', '19130', '19137', '19171', '19181', '19200', '19205', '19229', '19232', '19262', '19271', '19276', '19290', '19296', '19315', '19316', '19320', '19337', '19427', '19454', '19471', '19472', '1948', '19560', '19676', '20286', '20296', '20487', '20494', '20501', '20521', '20552', '20565', '20587', '20597', '20624', '20656', '20693', '20761', '20795', '20835', '20876', '20925', '20957', '21010', '21012', '21024', '21036', '21089', '21120', '21155', '21218', '21225', '21246', '21263', '21313', '21331', '21368', '21414', '21423', '21496', '21522', '21547', '21587', '21604', '21617', '21629', '21632', '2166', '21671', '21694', '21792', '21816', '21930', '22061', '22216', '22285', '22374', '22384', '22392', '22520', '22527', '22549', '22651', '22665', '2317', '2622', '2768', '29316', '29355', '29388', '29748', '29759', '29906', '29915', '3008', '3020', '30223', '3369', '3379', '3707', '3881', '38928', '38932', '38983', '39132', '3920', '39298', '39323', '39358', '39372', '39410', '39475', '39517', '39523', '39527', '39534', '39627', '39656', '39695', '39697', '39715', '39787', '39867', '39871', '4083', '4246', '4537', '4564', '4601', '5216', '5353', '5434', '5534', '5601', '5617', '5647', '5785', '5818', '5997', '6049', '6251', '6359', '6841', '6934', '6982', '7072', '7245', '7332', '7514', '7676', '7822', '8253', '8354', '8469', '8507', '8593', '8600', '8734', '9576', '9655', '9751', '9985', '9989'].
â       * Run identifier: 20210426-211158_faaef73f-1f15-4c9d-8dc6-d87277174843.
ââ      * Output spaces: MNI152NLin2009cAsym:res-2.
[2021-04-26 22:09:15,0239] [nipype.workflow ] [INFO     ] fMRIPrep workflow graph with 73080 nodes built successfully.
[2021-04-26 23:19:51,0371] [halfpipe        ] [INFO     ] Finished workflow d38ff754
[2021-04-26 23:22:17,0066] [halfpipe        ] [INFO     ] Initializing new execgraph d38ff754
[2021-04-27 02:07:33,0076] [nipype.workflow ] [INFO     ] Workflow nipype settings: ['check', 'execution', 'logging', 'monitoring']

**Comment by HippocampusGirl** [comment]
Hi Courtney,
That sounds problematic. To help me diagnose the problem, could you re-run with the option `--watchdog` at the end of the command? A few hours should be sufficient. Then, please send me the resulting log files.

**Comment by cchaswell** [comment]
I started from the beginning and it doesn't run very long now. It ends with this message:
<img width="500" alt="Screen Shot 2021-04-27 at 1 24 36 PM" src="https://user-images.githubusercontent.com/40609098/116285846-8da28400-a75c-11eb-9bae-f7b86a8ed632.png">

I might test with another data set just to see if there is an issue with this data. There are 234 functionals and 232 anatomicals so I thought maybe there was an issue with that. I assume that the program will only run the 232 subjects that match.

This is the log file, but err and workflow weren't created. 
[log.txt](https://github.com/HALFpipe/HALFpipe/files/6386472/log.txt)

**Comment by HippocampusGirl** [comment]
I think I know what the performance issue is, and plan to upload a bug fix soon

**Comment by HippocampusGirl** [comment]
Works for me now on `latest`. Please re-open if you continue having issues :-)
