### ISSUE TITLE
Group level processing stuck on "Matplotlib is building the font cache; this may take a moment."

### ISSUE THREAD

**Issue by kbkatebray** [HALFpipe/HALFpipe#107]
**What happened?**
I have completed the pre-processing/first level using Halfpipe and am attempting to run the group level statistics. I am using the cluster. I am using a very small subset of my data to test (8 participants). First level consisted of running seed-based connectivity and dual regression. Group level I just specified one linear model. 
I get the following messages in the terminal:
 [halfpipe        ] [IMPORTANT] Option "--verbose" was not specified. Will not print detailed logs to the terminal.
└─Detailed logs information will only be available in the "log.txt" file in the working directory.
Then "Matplotlib is building the font cache; this may take a moment." prints approximately 50 times and then nothing else happens. It can stay like this for a few hours. No group level directories are created.

**Is there an error message?**
No additional messages get printed to the log.txt, halfpipe.log.txt or err.txt files.

**What is the exact command that you used to run `Halfpipe`?**
To run the group level I ran the following commands:
Requesting interactive job on cluster : sinteractive -p interactive --time=01:00:00
load singularity: module load singularity/3.5.3
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.0.sif --only-model-chunk
Then the user interface opened, I selected my output directory and then selected 'Run without modification'.

**Which settings did you use?**
spec.json file contents attached in txt
[spec.json.txt](https://github.com/HALFpipe/HALFpipe/files/6402831/spec.json.txt)

Thanks in advance for your help!

**Comment by HippocampusGirl** [comment]
I did some testing, and it seems the issue comes from a missing environment variable. 

I will let you know once the fix is available for download so that you can test it.
