### ISSUE TITLE
How to re-run subjects that failed

### ISSUE THREAD

**Issue by alffajardo** [HALFpipe/HALFpipe#116]
Hello: 
I ran halpapipe with 76 subjects. However nearly 20 of them failed to run. I have strong reasons to believe that failures  were  not due to a haflpipe issue but to other issues in some   nodes of the cluster I am using (probably due to insufficient memory or cores available, or some other thing like this). I would like know how to run again only the subjects that failed.

Thanks in advance

**Comment by HippocampusGirl** [comment]
I have added the instructions to the manual here https://docs.google.com/document/d/108-XBIuwtJziRVVdOQv73MRgtK78wfc-NnVu-jSc9oI/edit#heading=h.aq341epb9phr

I will also add this to the documentation on GitHub

**Comment by HippocampusGirl** [comment]
Closing for now, please re-open if the documentation is still incomplete/unclear
