### ISSUE TITLE
Crash file created during fsl_glm command

### ISSUE THREAD

**Issue by YaraToenders** [HALFpipe/HALFpipe#126]
**What happened?**
In a sample of around 70 participants 422 crash files got created while running halfpipe. I'm not entirely sure it is a problem as it seems as if all (or most?) output files are in the derivatives folder 

**Is there an error message?**
See attached for crash file. 
[crash-20210531-074320-yatoenders-_glm40-7f506b65-fb8f-46b2-a0e5-41a967b6a624.txt](https://github.com/HALFpipe/HALFpipe/files/6585051/crash-20210531-074320-yatoenders-_glm40-7f506b65-fb8f-46b2-a0e5-41a967b6a624.txt)

RuntimeError: Command:
fsl_glm -i /ext/nipype/settings_wf/single_subject_2758_wf/func_preproc_task_rest_wf/gaussian_bandpass_filter_wf_6wxk/addmeans/mapflow/_addmeans0/blur_grandmeanscaled_regfilt_bptf_addmean.nii.gz -d /ext/nipype/features_wf/single_subject_2758_wf/func_preproc_task_rest_wf/seedCorr2_wf/fillna/mapflow/_fillna40/fillna_no_header.tsv -o beta.nii.gz -c /ext/nipype/features_wf/single_subject_2758_wf/func_preproc_task_rest_wf/seedCorr2_wf/contrasts/mapflow/_contrasts40/merge_no_header.tsv --demean -m /ext/nipype/fmriprep_wf/single_subject_2758_wf/func_preproc_task_rest_wf/bold_std_trans_wf/_std_target_MNI152NLin2009cAsym.res2/mask_std_tfm/ref_bold_corrected_brain_mask_maths_trans.nii.gz --out_cope=cope.nii.gz --out_varcb=varcope.nii.gz --out_z=zstat.nii.gz
Standard output:

Standard error:
terminate called after throwing an instance of 'NEWMAT::SingularException'
Aborted
Return code: 134

**What is the exact command that you used to run `Halfpipe`?**
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.1.sif --only-spec-ui
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.1.sif  --workdir /data/scratch/projects/punim0564/stanford_qMRI_ENIGMA_MDD/halfpipeoutput --use-cluster --skip-spec-ui
sbatch submit.slurm.sh

**Which settings did you use?**
Standard ENIGMA MDD settings (see spec.json)
[spec.json.txt](https://github.com/HALFpipe/HALFpipe/files/6585056/spec.json.txt)

**Comment by HippocampusGirl** [comment]
Could you also share `/data/scratch/projects/punim0564/stanford_qMRI_ENIGMA_MDD/halfpipeoutput/nipype/features_wf/single_subject_2758_wf/func_preproc_task_rest_wf/seedCorr2_wf/fillna/mapflow/_fillna40/fillna_no_header.tsv` and `/data/scratch/projects/punim0564/stanford_qMRI_ENIGMA_MDD/halfpipeoutput/nipype/features_wf/single_subject_2758_wf/func_preproc_task_rest_wf/seedCorr2_wf/contrasts/mapflow/_contrasts40/merge_no_header.tsv`?

**Comment by YaraToenders** [comment]
Yes, see below!
(Hope it's not a problem that I made them text files, otherwise they cannot be uploaded)
[merge_no_header.tsv.txt](https://github.com/HALFpipe/HALFpipe/files/6585293/merge_no_header.tsv.txt)
[fillna_no_header.tsv.txt](https://github.com/HALFpipe/HALFpipe/files/6585294/fillna_no_header.tsv.txt)

**Comment by YaraToenders** [comment]
Hi Lea, 
We realised that these resting state images still had dummy scans at the beginning, after removing them and rerunning HALFpipe the crash files weren't created again. So I think this was the reason of the crash files.

**Comment by HippocampusGirl** [comment]
Interesting! This means that fMRIPrep's automatic detection of non-steady state volumes at the start might be a good think to add back in after all. What do you think @YaraToenders @ilyaveer ?
