### ISSUE TITLE
BrokenProcessPool

### ISSUE THREAD

**Issue by acalvet-idi** [HALFpipe/HALFpipe#134]
**What happened?**
While running halfpipe version 1.1.0, after a week, an error occurred (a process in the process pool was terminated abruptly while the future was running or pending), the process seems unfinished, however, no new output is generated.
Sample size is 103 subjects. The generated output in /path/to/working/directory/derivates/halfpipe/ there are 56 folders with around 1500 files, except for 4 that only have 86 files.

**Is there an error message?**
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending
Please copy it here. `err.txt` file attached for more information. 
[err.txt](https://github.com/HALFpipe/HALFpipe/files/6685941/err.txt)

**What is the exact command that you used to run `Halfpipe`?**
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.0.sif --verbose

**Which settings did you use?**
[spec.txt](https://github.com/HALFpipe/HALFpipe/files/6686001/spec.txt)

**Comment by HippocampusGirl** [comment]
Dear @acalvet-idi,
Could you try the suggestions listed here: https://github.com/HALFpipe/HALFpipe/discussions/133
If they don't work, please re-open :-)
