### ISSUE TITLE
Problem with choosing the non-BIDS format option

### ISSUE THREAD

**Issue by haemepark** [HALFpipe/HALFpipe#135]
Hi there,

I'm trying to specify my paths for the T1 and EPI images; however, am having a problem with choosing the 'No' option to the question "Is the data available in BIDS format?". When I choose 'No', I get this error:

```
Traceback (most recent call last):

File "/usr/local/miniconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner

self.run()

File "/usr/local/miniconda/lib/python3.7/threading.py", line 865, in run

self._target(*self._args, **self._kwargs)

File "/usr/local/miniconda/lib/python3.7/site-packages/calamities/input/pattern.py", line 286, in _scan_files_loop

suggestionstr = suggestion_match.sub(tagdict["suggestion"], suggestiontempl)

File "/usr/local/miniconda/lib/python3.7/re.py", line 309, in _subx

template = _compile_repl(template, pattern)

File "/usr/local/miniconda/lib/python3.7/re.py", line 300, in _compile_repl

return sre_parse.parse_template(repl, pattern)

File "/usr/local/miniconda/lib/python3.7/sre_parse.py", line 1018, in parse_template

addgroup(int(this[1:]), len(this) - 1)

File "/usr/local/miniconda/lib/python3.7/sre_parse.py", line 962, in addgroup

raise s.error("invalid group reference %d" % index, pos)

re.error: invalid group reference 2 at position 3
```

The next question does come up (e.g., "Specify the path of the T1-weighted image files", but it doesn't accept (or find any folders with /) anything I type in (i.e., I press enter but nothing happens). Any pointers/help would be much appreciated - thank you!

**Comment by haemepark** [comment]
Just to add - when I select 'Yes' to the BIDS format question, I'm able to proceed and specify a path for the files (which doesn't work as my files are not in the BIDS format, so it returns:
```
Found 0 T1-weighted image files
Found 0 BOLD image files
```
Thanks!

**Comment by HippocampusGirl** [comment]
Could you send me the entire `log.txt` and `err.txt` files from your working directory?

**Comment by yannquide** [comment]
Hi Lea, I have the same issue here. Using docker, on either Mac or Windows machine. 
It does not create the err.txt or log.txt files, or it is stored somewhere I am not aware of?

**Comment by HippocampusGirl** [comment]
Interesting! Could you confirm which version of HALFpipe you are using? Did anything change about your system between now and when you were last able to use HALFpipe?

**Comment by yannquide** [comment]
This happened to me with both 1.1.0 and 1.1.1. I tried on various machines, various OS and various locations (eg home or work) to troubleshoot any of these details (eg same OS in 2 locations, different OS in same location, Windows vs Mac). In some instances (eg Mac at work), the halfpipe welcome page does not even load (blank page). Have you ever seen this behaviour before?

**Comment by HippocampusGirl** [comment]
> In some instances (eg Mac at work), the halfpipe welcome page does not even load (blank page). Have you ever seen this behaviour before?

This happens when the Docker for Mac memory (RAM) limit is set very low (which is the default). You should increase it to at least 8 GB in the settings.
