### ISSUE TITLE
Distorted carpet plots

### ISSUE THREAD

**Issue by HippocampusGirl** [HALFpipe/HALFpipe#16]
**What happened?**
At random, carpet plots can be distorted.
![sub-99_epi_confounds](https://user-images.githubusercontent.com/789054/97916222-faf7ce00-1d52-11eb-9ce7-dc05f64c3874.png)

**Comment by ilyaveer** [comment]
@HippocampusGirl what do you mean with distorted? Or am I not seeing something strange in the above example?

**Comment by HippocampusGirl** [comment]
> @HippocampusGirl what do you mean with distorted? Or am I not seeing something strange in the above example?

Well the background of the plot is black, not white, so you cannot read the labels. Also the plot is much wider than I would prefer for readability.

**Comment by HippocampusGirl** [comment]
I have not seen this occur in quite some time
