### ISSUE TITLE
Error creating the workflow files

### ISSUE THREAD

**Issue by Hannah-Savage** [HALFpipe/HALFpipe#213]
Hi Lea and team,

I've been trying to get halfpipe to run with default settings (before testing out the plug in you wrote for me - thanks again!) but keep running into the issue below. A few colleagues have had a similar issue but applying their fixes hasn't worked for me. Hoping you can help!

Thanks,
Hannah

**What happened?**
1. I have 3 subjects data (ID = 0005/6/7) in my working directory on an HPC server.
2. I loaded the module [module load singularity/3.5.3]
3. I downloaded the latest  halfpipe [curl -O https://download.fmri.science/singularity/halfpipe-halfpipe-1.2.0.sif]
4. I ran [singularity run --no-home --cleanenv --bind /:/ext /data/projects/punim1042/7TRS/halfpipe-halfpipe-1.2.0.sif --only-spec-ui]
5. I specified the following
*NOT in BIDS format*--> it detected 3 subjects files (which is correct).
Scans acquired: inferior to superior as detected
Slice timing: as detected
No scans removed
No field maps specified
Smoothing 3.2mm
Grand mean scaling NO
Temporal Filer: frquency based: 0.01-0.1
Removing: ICA-Aroma, Motion parameters, Derivatives of motion parameters, aCompCor, WM, CSF
No other outputs.

![Specifying](https://user-images.githubusercontent.com/69136072/134869998-6654be20-41db-435c-b5ef-10bae86e7907.png)

**Is there an error message?**
6. It fails when I run [singularity run --containall --bind /:/ext halfpipe-halfpipe-1.2.0.sif --workdir /ext/data/projects/punim1042/7TRS/ --use-cluster --skip-spec-ui]
It is able to create the derivatives, nipype and raw data folders, but seems unable to then retrieve the subject information to fill them.

![Screen Shot 2021-09-27 at 6 17 05 pm](https://user-images.githubusercontent.com/69136072/134870598-805b688d-d2e8-4bb4-b5af-f86be92e3dd7.png)

The log.txt file it also attached.
[log.txt](https://github.com/HALFpipe/HALFpipe/files/7234540/log.txt)

**What is the exact command that you used to run `Halfpipe`?**
see above.

**Which settings did you use?**
Please see above and the attached spec_json.txt file. (couldn't upload as a .json file sorry!)
[spec_json.txt](https://github.com/HALFpipe/HALFpipe/files/7234547/spec_json.txt)

**Comment by HippocampusGirl** [comment]
As far as I can tell, you are using the same directory for your raw data and also as a working directory. I remember that this caused problems with another user a while ago.
Could you try using separate directories? For example, keeping the data in `/data/projects/punim1042/7TRS` and then running `HALFpipe` in `/data/projects/punim1042/7TRS_workdir`.

**Comment by Hannah-Savage** [comment]
Hi Lea,

Thanks for your reply. I restructured the data like this: 

Moved my subject data into: 
/data/projects/punim1042/7TRS_data/
/data/projects/punim1042/7TRS_data/005 
/data/projects/punim1042/7TRS_data/006 
/data/projects/punim1042/7TRS_data/007 

Made a new folder that contains halfpipe-halfpipe-1.2.0.sif
/data/projects/punim1042/7TRS_workdir/
/data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif

I then ran steps 1,4 and 5 (as above) from within the /data/projects/punim1042/7TRS_workdir folder (this created the .json file that was saved in  /data/projects/punim1042/7TRS_workdir/). 

I then ran step 6 (from within the /data/projects/punim1042/7TRS_workdir), and got the same error message as before. Again, as before, when I specified the settings, it was able to detect my 3 subjects, but it seems unable to access them, and is also suggesting that I have BIDS formatted data. It has updated the path to where the new files should be... 

![Screen Shot 2021-09-30 at 10 58 30 am](https://user-images.githubusercontent.com/69136072/135368484-1b160002-f20a-42c3-8dc5-482dac4fb9cc.png)

Do you have any other idea what might be causing this issue?

Thanks in advance for your time troubleshooting.

Kind regards,
Hannah

**Comment by HippocampusGirl** [comment]
This is incredibly confusing, because it seems to work in the user interface, but then not anymore when you restart

**Comment by HippocampusGirl** [comment]
Could you send me the full directory structure of your data directory (i.e., the output of `find -L /data/projects/punim1042/7TRS_data/`)?

**Comment by Hannah-Savage** [comment]
Sure :)

>>find -L /data/projects/punim1042/7TRS_data/
/data/projects/punim1042/7TRS_data/
/data/projects/punim1042/7TRS_data/006
/data/projects/punim1042/7TRS_data/006/task
/data/projects/punim1042/7TRS_data/006/task/006_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/006/task/006_task-rest_bold.json
/data/projects/punim1042/7TRS_data/006/anat
/data/projects/punim1042/7TRS_data/006/anat/006_T1w.json
/data/projects/punim1042/7TRS_data/006/anat/006_T1w.nii
/data/projects/punim1042/7TRS_data/007
/data/projects/punim1042/7TRS_data/007/task
/data/projects/punim1042/7TRS_data/007/task/007_task-rest_bold.json
/data/projects/punim1042/7TRS_data/007/task/007_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/007/anat
/data/projects/punim1042/7TRS_data/007/anat/007_T1w.json
/data/projects/punim1042/7TRS_data/007/anat/007_T1w.nii
/data/projects/punim1042/7TRS_data/005
/data/projects/punim1042/7TRS_data/005/task
/data/projects/punim1042/7TRS_data/005/task/005_task-rest_bold.json
/data/projects/punim1042/7TRS_data/005/task/005_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/005/anat
/data/projects/punim1042/7TRS_data/005/anat/005_T1w.json
/data/projects/punim1042/7TRS_data/005/anat/005_T1w.nii

**Comment by HippocampusGirl** [comment]
Could you also run `singularity exec --containall --bind /:/ext halfpipe-halfpipe-1.2.0.sif find -L /ext/data/projects/punim1042/7TRS_data/` to verify that it also works inside Singularity?

**Comment by Hannah-Savage** [comment]
Seems it's not able to: 
[hssavage@spartan-login2 punim1042]$ cd 7TRS_workdir
[hssavage@spartan-login2 7TRS_workdir]$ singularity exec --containall --bind /:/ext halfpipe-halfpipe-1.2.0.sif find -L /ext/data/projects/punim1042/7TRS_data/
find: ‘/ext/data/projects/punim1042/7TRS_data/’: No such file or directory

**Comment by HippocampusGirl** [comment]
Awesome, that means we have found the issue :-) Apparently your system does not support just binding everything in `/` into the container.

Could you try binding `/data` directly into the container? `singularity exec --containall --bind /data:/data halfpipe-halfpipe-1.2.0.sif find -L /data/projects/punim1042/7TRS_data/`

If that works, you should be able to use `--bind /data:/data` instead of `--bind /:/ext` for all the commands. Note that you will need to re-generate your `spec.json`, as it contains references to `/ext`.

**Comment by Hannah-Savage** [comment]
That works!

[hssavage@spartan-login2 7TRS_workdir]$ singularity exec --containall --bind /data:/data halfpipe-halfpipe-1.2.0.sif find -L /data/projects/punim1042/7TRS_data/
/data/projects/punim1042/7TRS_data/
/data/projects/punim1042/7TRS_data/006
/data/projects/punim1042/7TRS_data/006/task
/data/projects/punim1042/7TRS_data/006/task/006_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/006/task/006_task-rest_bold.json
/data/projects/punim1042/7TRS_data/006/anat
/data/projects/punim1042/7TRS_data/006/anat/006_T1w.json
/data/projects/punim1042/7TRS_data/006/anat/006_T1w.nii
/data/projects/punim1042/7TRS_data/007
/data/projects/punim1042/7TRS_data/007/task
/data/projects/punim1042/7TRS_data/007/task/007_task-rest_bold.json
/data/projects/punim1042/7TRS_data/007/task/007_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/007/anat
/data/projects/punim1042/7TRS_data/007/anat/007_T1w.json
/data/projects/punim1042/7TRS_data/007/anat/007_T1w.nii
/data/projects/punim1042/7TRS_data/005
/data/projects/punim1042/7TRS_data/005/task
/data/projects/punim1042/7TRS_data/005/task/005_task-rest_bold.json
/data/projects/punim1042/7TRS_data/005/task/005_task-rest_bold.nii
/data/projects/punim1042/7TRS_data/005/anat
/data/projects/punim1042/7TRS_data/005/anat/005_T1w.json
/data/projects/punim1042/7TRS_data/005/anat/005_T1w.nii


ok so step 4 above becomes: 
[singularity run --no-home --cleanenv --bind **/data:**/data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --only-spec-ui]

and step 6:
[singularity run --containall --bind **/data:**/data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --workdir /ext/data/projects/punim1042/7TRS/ --use-cluster --skip-spec-ui]

is that correct?

**Comment by HippocampusGirl** [comment]
This looks fine, but don't forget the space between the `--bind /data:/data` and the path to the container :-)

You can also do steps 4 and 6 at the same time via
`singularity run --containall --bind /data:/data /projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --use-cluster`

**Comment by Hannah-Savage** [comment]
Ok! I will give the commands below a try tomorrow (or your combined version) and let you know how I go :) Thanks so much for your help! 
____________________________________________________________________
Updated commands I will run:

step 4:
[singularity run --no-home --cleanenv --bind /data:/data /data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --only-spec-ui]

and step 6:
[singularity run --containall --bind /data:/data /data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --workdir /ext/data/projects/punim1042/7TRS_workdir/ --use-cluster --skip-spec-ui]

**Comment by Hannah-Savage** [comment]
Hey Lea,

When I ran step 4: 
[singularity run --no-home --cleanenv --bind /data:/data /data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --only-spec-ui] I got the following warning: 
WARNING: Bind mount '/data => /data' overlaps container CWD /data/projects/punim1042, may not be available

It then had the following error:
singularity run --containall --bind /data:/data /data/projects/punim1042/7TRS_workdir/halfpipe-halfpipe-1.2.0.sif --workdir /data/projects/punim1042/7TRS_workdir/ --use-cluster --skip-spec-ui
[2021-09-30 23:06:25,0833] [halfpipe        ] [ERROR    ] Exception: Cannot use "/ext/data/projects/punim1042/7TRS_workdir/" as working directory for HALFpipe. Please check that you have sufficient permissions. Please also check that you are using a file system that supports symbolic links. For example, FAT32 and exFAT are incompatible.

I then deleted all the log files, previous error files and the old .json file and respecified it all and ran these two steps again. 
I got the same warning for step 4, but Step 6 now returns a 'STRING INDEX OUT OF RANGE' error. I have had this multiple times before (before the BIDS error above came about). When this happens it doesn't even get to make the folders (as it had with my BIDS error). 
I've attached the log file and the new .json file, if you might be able to see why this is occurring... 

[log.txt](https://github.com/HALFpipe/HALFpipe/files/7262996/log.txt)
[spec_json.txt](https://github.com/HALFpipe/HALFpipe/files/7262998/spec_json.txt)

Out of interest I ran this command from within my working directory [singularity exec --containall --bind /data:/data halfpipe-halfpipe-1.2.0.sif find -L] and all it returned was (a single full stop):
.

Let me know if there's anything else that would be helpful to know!

**Comment by HippocampusGirl** [comment]
I think you left the task name field empty. If you're using resting state data, you can put "rest". I will add a check to the code so that this gives a proper error message

**Comment by HippocampusGirl** [comment]
I am closing the issue for now, because I think it was resolved. Please re-open if this is not the case :-)
