### ISSUE TITLE
Error when running halfpipe 1.2.1

### ISSUE THREAD

**Issue by trishcqh** [HALFpipe/HALFpipe#243]
Dear Lea and team,

I've been trying to run halfpipe 1.2.1 on our data and have encountered an error that did not appear on our previous run of halfpipe 1.1.0.

We are running it locally on a mac using docker and the previous spec.json file (run without modifications).

The error message is as follows:
"ERRO[235050] error waiting for container: invalid character 'u' looking for beginning of value"

Attached is the [err.txt](https://github.com/HALFpipe/HALFpipe/files/7414890/err.txt) file for your reference as well. Apologies, I do not seem to be able to upload the log.txt file here. Please let me know if any further information is required. 

Thank you!

Regards,
Tricia

**Comment by HippocampusGirl** [comment]
Dear Tricia,

Did you have any success trying the strategies suggested in <https://github.com/docker/for-mac/issues/5139>? 

Best,
Lea

**Comment by trishcqh** [comment]
Dear Lea,

Apologies for missing out on your email! I just re-ran the incomplete
subjects as you suggested previously and managed to generate the output
necessary without having to use the solutions suggested in the thread.
Thanks so much for checking in

Regards,
Tricia
