### ISSUE TITLE
Requirements for atlas used in atlas based connectivity 

### ISSUE THREAD

**Issue by richardbeare** [HALFpipe/HALFpipe#248]
**What happened?**
I've specified an atlas from https://github.com/neurodata/neuroparc.git, specifically 

`neuroparc/atlases/label/Human/DKT_space-MNI152NLin6_res-2x2x2.nii.gz`

I've also copied the corresponding json from the subfolder into the same folder

**Is there an error message?** 
After specifying the atlas name (I used DKT), I receive the following:

`Expecting value: line 1 column 1 (char 0)`

**What is the exact command that you used to run `Halfpipe`?**
`singularity run --containall --bind myfolder:/ext halfpipe-halfpipe-latest.sif --use-cluster --workdir /ext/PETS/work/

**Which settings did you use?**

This occurred during setup.

What is the expected format/naming etc of atlas files?
Thanks

**Comment by HippocampusGirl** [comment]
Dear @richardbeare, 

Is there an `err.txt` or `log.txt` file in your working directory? Could you upload it/send it to me?

**Comment by richardbeare** [comment]
@HippocampusGirl  - I've attached the two files:

[err.txt](https://github.com/HALFpipe/HALFpipe/files/7452545/err.txt)
[log.txt](https://github.com/HALFpipe/HALFpipe/files/7452548/log.txt)

**Comment by HippocampusGirl** [comment]
The error looks like you are trying to clone a repository that is using Git Large File Storage (LFS) to store its data, but you do not have the `git-lfs` extension for `git` installed. Please install `git-lfs` and try cloning the atlases again :-)

**Comment by richardbeare** [comment]
That's embarrassing! Well spotted.

If anyone else wants to use the same atlas set - it turns out that you are better off fetching from osf(https://osf.io/67a3t/) - github will complain about lsf data bandwidth.
