### ISSUE TITLE
Warnings Ignored  validation error for BIDs data 

### ISSUE THREAD

**Issue by shrimpj** [HALFpipe/HALFpipe#253]
**What happened?**
Tons of error messages popped up stating 'Ignored validation error for /ext/<BIDS data path>.txt": {'suffix': ['Unsupported value: xfm']}. When python was launched to execute halfpipe, the process terminated.

**Is there an error message?**
![image](https://user-images.githubusercontent.com/16172014/140384016-6945caea-1502-437a-be73-6b4f059ed6c7.png)

**What is the exact command that you used to run `Halfpipe`?**
singularity run --no-home --cleanenv --bind /:/ext halfpipe_1.1.1.sif

**Which settings did you use?**
the default for resting data analysis

**Comment by HippocampusGirl** [comment]
The `illegal instruction` error suggests that you may be using either a very old or very new processor that is not supported by `ANTs`. Are you using Linux or Mac OS? Which model is your CPU?

**Comment by shrimpj** [comment]
I am using Linux from the University and I believe it's been updated recently to CENTOS7. I wonder if there is a way I can fix the problem? Thanks

**Comment by shrimpj** [comment]
> The `illegal instruction` error suggests that you may be using either a very old or very new processor that is not supported by `ANTs`. Are you using Linux or Mac OS? Which model is your CPU?

I am using Linux from the university and I believe it's been updated recently to CENTOS7. I wonder if there is a way I can fix the problem? Thanks

**Comment by HippocampusGirl** [comment]
Could you post the output from `cat /proc/cpuinfo` on your system? This will show some information about your processor that will help me to diagnose the issue.

**Comment by shrimpj** [comment]
> Could you post the output from `cat /proc/cpuinfo` on your system? This will show some information about your processor that will help me to diagnose the issue.

HippocampusGirl, Thank you so much for your reply. Please see attached screenshot.
![image](https://user-images.githubusercontent.com/16172014/142193756-3c6dfe28-b735-453a-9446-8e2c90eaf1ac.png)

**Comment by shrimpj** [comment]
> Could you post the output from `cat /proc/cpuinfo` on your system? This will show some information about your processor that will help me to diagnose the issue.


Does any member from the HALFpipe group could answer my questions? Thanks

**Comment by HippocampusGirl** [comment]
Dear @shrimpj,

Your screenshot indicates that your CPU is sufficiently recent to support running HALFpipe. We actually have a similar setup at my workplace. I am unsure what exactly could cause this error when running `antsRegistration`. Could you ask your university about the `illegal instruction` message from the screenshot?

**Comment by HippocampusGirl** [comment]
Since there has been no response, I assume that the issue has been solved. Please re-open if you are still having problems :-)
