### ISSUE TITLE
Error during Slice-timing correction 

### ISSUE THREAD

**Issue by bvv92** [HALFpipe/HALFpipe#342]
**What happened?**

I got an error during slice-timing correction step. It seems like Halfpipe created a broken link (/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_subject_con37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-con37_task-rest_bold.nii.gz) to a file located in (/ext/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreNeSt_1/rawdata/sub-con37/func/sub-con37_task-rest_bold.nii.gz)
I assume it could be happening due to additional /ext directory, which it writes even if I did not put in anywhere in the user interface. It happens for every subject I put into Halfpipe recently, yet couple of weeks before when I worked with another dataset, I did not encounter this problem.

**Is there an error message?**

File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/plugins/multiproc.py", line 72, in run_node
    50   def run_node(node, updatehash, taskid):
 (...)
    68       result: Dict[str, Any] = dict(result=None, traceback=None, taskid=taskid)
    69   
    70       # Try and execute the node via node.run()
    71       try:
--> 72           result["result"] = node.run(updatehash=updatehash)
    73       except Exception:  # catch all here
    ..................................................
     node = nipype.fmriprep_wf.single_subject_con37_wf.func_preproc_task
             _rest_wf.bold_stc_wf.slice_timing_correction
     updatehash = False
     taskid = 302
     result = {'result': None,
               'traceback': None,
               'taskid': 302}
     Dict = typing.Dict
     Any = typing.Any
     node.run = <method 'Node.run' of nipype.fmriprep_wf.single_subject_con3
                 7_wf.func_preproc_task_rest_wf.bold_stc_wf.slice_timing_corr
                 ection nodes.py:427>
    ..................................................

File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    427  def run(self, updatehash=False):
 (...)
    520      savepkl(op.join(outdir, "_node.pklz"), self)
    521      savepkl(op.join(outdir, "_inputs.pklz"), self.inputs.get_traitsfree())
    522  
    523      try:
--> 524          result = self._run_interface(execute=True)
    525      except Exception:
    ..................................................
     self = nipype.fmriprep_wf.single_subject_con37_wf.func_preproc_task
             _rest_wf.bold_stc_wf.slice_timing_correction
     updatehash = False
     op.join = <function 'join' posixpath.py:71>
     outdir = '/ext/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreN
               eSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_subject_co
               n37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_co
               rrection'
     self.inputs.get_traitsfree = <method 'BaseTraitedSpec.get_traitsfree' of 
                                  args = <undefined>
                                  environ = {}
                                  ignore = 0
                                  in_file = /ext/media/admin_lokal/DATA2/Vladimir/Halfpipe_pre
                                   proc/PreNeSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_s
                                   ubject_con37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_
                                   timing_correction/sub-con37_task-rest_bold.nii.gz
                                  interp = <undefined>
                                  num_threads = 1
                                  out_file = <undefined>
                                  outputtype = NIFTI_GZ
                                  rlt = <undefined>
                                  rltplus = <undefined>
                                  slice_encoding_direction = k
                                  slice_timing = [0.0, 0.07176174...
     self._run_interface = <method 'Node._run_interface' of nipype.fmriprep_wf.single_s
                            ubject_con37_wf.func_preproc_task_rest_wf.bold_stc_wf.slice_
                            timing_correction nodes.py:638>
    ..................................................

File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    638  def _run_interface(self, execute=True, updatehash=False):
    639      if updatehash:
    640          self._update_hash()
    641          return self._load_results()
--> 642      return self._run_command(execute)
    ..................................................
     self = nipype.fmriprep_wf.single_subject_con37_wf.func_preproc_task
             _rest_wf.bold_stc_wf.slice_timing_correction
     execute = True
     updatehash = False
     self._update_hash = <method 'Node._update_hash' of nipype.fmriprep_wf.single_sub
                          ject_con37_wf.func_preproc_task_rest_wf.bold_stc_wf.slice_ti
                          ming_correction nodes.py:633>
     self._load_results = <method 'Node._load_results' of nipype.fmriprep_wf.single_su
                           bject_con37_wf.func_preproc_task_rest_wf.bold_stc_wf.slice_t
                           iming_correction nodes.py:644>
     self._run_command = <method 'Node._run_command' of nipype.fmriprep_wf.single_sub
                          ject_con37_wf.func_preproc_task_rest_wf.bold_stc_wf.slice_ti
                          ming_correction nodes.py:690>
    ..................................................

File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    690  def _run_command(self, execute, copyfiles=True):
 (...)
    746          rebase=str2bool(self.config["execution"]["use_relative_paths"]),
    747      )
    748  
    749      if exc_tb:
--> 750          raise NodeExecutionError(
    751              f"Exception raised while executing Node {self.name}.\n\n{result.runtime.traceback}"
    ..................................................
     self = nipype.fmriprep_wf.single_subject_con37_wf.func_preproc_task
             _rest_wf.bold_stc_wf.slice_timing_correction
     execute = True
     copyfiles = True
     self.config = {'logging': {'workflow_level': 'INFO',
                                'utils_level': 'INFO',
                                'interface_level': 'INFO',
                                'log_to_file': 'false',
                                'log_directory': '/home/admin_lokal',
                                'log_size': '16384000',
                                'log_rotate': '4'},
                    'execution': {'create_report': True,
                                  'crashdump_dir': PosixPath('/ext/media/admin_
                    lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreN
                    eSt_1'),
                                  'hash_method': 'timestamp',
                                  'j...
     exc_tb = 'Traceback (most recent call last):\n  File "/usr/local/mini
               conda/lib/python3.10/site-packages/nipype/interfaces/base/co
               re.py", line 454, in aggregate_outputs\n    setattr(outputs,
                key, val)\n  File "/usr/local/miniconda/lib/python3.10/site
               -packages/nipype/interfaces/base/traits_extension.py", line 
               330, in validate\n    value = super(File, self).validate(obj
               ekt, name, value, return_pathlike=True)\n  File "/usr/local/
               miniconda/lib/python3.10/site-packages/nipype/interfaces/bas
               e/traits_extension.p...
     NodeExecutionError = <class 'nipype.pipeline.engine.nodes.NodeExecutionError'>
    ..................................................

---- (full traceback above) ----
File "/usr/local/miniconda/lib/python3.10/site-packages/halfpipe/plugins/multiproc.py", line 72, in run_node
    result["result"] = node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(

NodeExecutionError: Exception raised while executing Node slice_timing_correction.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/traits_slicextension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a TShiftOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/ext/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_subject_con37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-con37_task-rest_bold_tshift.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/ext/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_subject_con37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-con37_task-rest_bold_tshift.nii.gz' for output 'out_file' of a TShift interface

**Which settings did you use?**

Ubuntu 18.04.5 LTS
singularity-2.5.2
halfpipe-halfpipe-latest.simg

**Comment by HippocampusGirl** [comment]
Hi @bvv92,

You can disable the addition of `/ext` by adding the command line flag `--fs-root /` when you start the container. Which command do you use to start `HALFpipe`?

**Comment by bvv92** [comment]
Hi Lea,

I tried 
1) singularity run --cleanenv  --containall --bind /:/ext /home/admin_lokal/singularity-2.5.2/halfpipe-halfpipe-latest.simg

and 
2) singularity run --cleanenv  --containall --bind /media/ /home/admin_lokal/singularity-2.5.2/halfpipe-halfpipe-latest.simg

Same error as before (FileNotFoundError: No such file or directory '/media/admin_lokal/DATA2/Vladimir/Halfpipe_preproc/PreNeSt_HC/Output_PreNeSt_1/nipype/fmriprep_wf/single_subject_con37_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-con37_task-rest_bold_tshift.nii.gz for output 'out_file' of a TShift interface)

My mistake though, apparently the problem is not about the broken link, as there is only sub-con37_task-rest_bold.nii.gz file in slice_timing_correction folder but not sub-con37_task-rest_bold_tshift.nii.gz

**Comment by HippocampusGirl** [comment]
Hi @bvv92,

Thank you! I think I understand the issue better now. It seems to me that it tries to run slice timing, but fails. Could you send me the full log file from your run? You can either upload here or send me an e-mail at <lea.waller@charite.de>.
