### ISSUE TITLE
File missing when running HALFpipe

### ISSUE THREAD

**Issue by YaraToenders** [HALFpipe/HALFpipe#360]
**What happened?**
HALFpipe seems to hang (it continues running but no more output gets created). The 'tpl-OASIS30ANTs_res-01_T1w_maths.nii.gz' file seems to be missing.

**Is there an error message?**
traits.trait_errors.TraitError: The 'output_image' trait of an ImageMathOuputSpec instance must be a pathlike object or string representing an existing file, but a value of '/gpfs/scratch1/shared/emesek/OutHALFpipe/nipype/fmriprep_wf/single_subject_sub1032_wf/anat_preproc_wf/brain_extraction_wf/lap_tmpl/tpl-OASIS30ANTs_res-01_T1w_maths.nii.gz' <class 'str'> was specified. 

(full error log attached)
[err.txt](https://github.com/HALFpipe/HALFpipe/files/8973871/err.txt)
[log.txt](https://github.com/HALFpipe/HALFpipe/files/8973872/log.txt)

**What is the exact command that you used to run `Halfpipe`?**
singularity run --no-mount hostfs --containall --bind /scratch-shared/emesek/:/ext/scratch-shared/emesek/ /home/emesek/software/halfpipe-halfpipe-1.2.2.sif --use-cluster --fs-license-file /home/emesek/software/license.txt
sbatch submit.slurm.sh

**Which settings did you use?**
Spec.json converted to txt. 
[spec.json.txt](https://github.com/HALFpipe/HALFpipe/files/8973875/spec.json.txt)

**Comment by HippocampusGirl** [comment]
Hi Yara,

That is weird, it seems like the step failed to generate an output file, but there was no error.

Could you send me
- A directory listing of `/gpfs/scratch1/shared/emesek/OutHALFpipe/nipype/fmriprep_wf/single_subject_sub1032_wf/anat_preproc_wf/brain_extraction_wf/lap_tmpl/`
- If there is a `_report/report.rst` in that directory, could you send me that file?

**Comment by HippocampusGirl** [comment]
That looks fine, there does not seem to be any issue there. That means that the actual issue was most likely the command being run failing for some reason, without giving us a proper error message.

I think we will need to take the command from the `command.txt` file there and try to run it from inside the container. This will tell us what went wrong, and why it didn't generate the output file. Do you have time for a quick video call?

**Comment by YaraToenders** [comment]
Sorry, only seeing this now. Really appreciate your help! I'll send you an email to find a time!
