### ISSUE TITLE
curses.error: addwstr() returned ERR

### ISSUE THREAD

**Issue by Laura-CAH** [HALFpipe/HALFpipe#420]
**What happened?**
After the step "Specify the feature name", appears the message "Specify images to use" and then, the HALFpipe interface close. The error in the last code line says "curses.error: addwstr() returned ERR"

**Is there an error message?**
Please copy it here. If you are unsure, please provide the contents of the `err.txt` file from your `Halfpipe` working directory. Note that this log file may contain filenames from your computer.

**What is the exact command that you used to run `Halfpipe`?**
sudo docker run --interactive --tty --volume /:/ext halfpipe/halfpipe --fs-license-file /home/laura/Documents/HALFpipe/license.txt --verbose

**Which settings did you use?**
I do not have the `spec.json` file  in the Halfpipe working directory

**Comment by HippocampusGirl** [comment]
This may me a duplicate of #400. How many distinct sessions or runs do you have in your data?

**Comment by HippocampusGirl** [comment]
Since we have recently fixed the highly similar issue #400, I am going to assume that we solved this one as well :-) Please feel free to re-open the issue if it re-occurs with the "latest" version.
