### ISSUE TITLE
Cannot delete nipype folder in latest version

### ISSUE THREAD

**Issue by cchaswell** [HALFpipe/HALFpipe#43]
**What happened?**
After running halfpipe, I usually delete the nipype folder before copying over data to our storage server. 

**Is there an error message?**
I get a bunch of messages that it cannot be deleted due to a read-only filesystem.

**What is the exact command that you used to run `Halfpipe`?**
rm -rf nipype

**Which settings did you use?**
Since this was the first batch I ran the latest halfpipe version with, I wanted to see if something changed at all in the code that would do something with that folder. I am also asking my cluster admin about that server and deleting the folder. Would anything have changed in the newest pipeline version that would do that?

**Comment by HippocampusGirl** [comment]
I cannot imagine how HALFpipe could affect the file system. As far as I can tell, a "read-only filesystem" error is distinct from a "permission denied" error. Usually only administrators can influence whether the file system is read-only or read-write.

**Comment by cchaswell** [comment]
It was an issue with our server being updated over the weekend, and the
cluster blades needed to be restarted for it to work right. I didn't think
it was an issue with the pipeline, but because it was the first time I ran
the new version I just figured I would ask. You can close this issue out :)
