### ISSUE TITLE
Slice Timing - import from file

### ISSUE THREAD

**Issue by cchaswell** [HALFpipe/HALFpipe#55]
**What happened?**
I got an error when I try to use "import from file" for slice timing parameters

**Is there an error message?**
Error that it must be one of the choices sequential increasing, etc. 

This is the version I downloaded right after the original fix for even/odd slice timing mix ups.
<img width="1286" alt="Screen Shot 2021-02-22 at 10 15 07 AM" src="https://user-images.githubusercontent.com/40609098/108728134-46e3a400-74f7-11eb-92e4-ac085fe66e9c.png">

**Comment by HippocampusGirl** [comment]
Could you provide me with the err.txt file from the working directory?

**Comment by cchaswell** [comment]
Here it is. 
[err.txt](https://github.com/HALFpipe/HALFpipe/files/6036569/err.txt)
