### ISSUE TITLE
There's no file "execgraph.{n_chunks}_chunks.{uuid}.pickle.xz" generated, and there's an error message saying that "halfpipe: error: argument --only-chunk-index: expected one argument".

### ISSUE THREAD

**Issue by ruiyangge** [HALFpipe/HALFpipe#631]
**What happened?**
Hi Lea, thanks for this wonderful tool. 
I recently had an issue using it, I can successfully generate the intermediate file "workflow.{uuid}.pickle.xz" and ".flat_graph.{uuid}.pickle.xz" but there's no "execgraph.{n_chunks}_chunks.{uuid}.pickle.xz" file. Therefore, when I used my "submit.torque.sh" file to run the program, there's an error message, saying that "halfpipe: error: argument --only-chunk-index: expected one argument".
![all_files](https://github.com/HALFpipe/HALFpipe/assets/9414983/860fe665-b356-4913-9089-e168027a0848)
Thanks for your help!

**Is there an error message?**
Please copy it here. If you are unsure, please provide the contents of the `err.txt` file from your `Halfpipe` working directory. Note that this log file may contain filenames from your computer.
![error_message](https://github.com/HALFpipe/HALFpipe/assets/9414983/d6136175-f4d5-48e5-b1f5-a49ff7443743)
[err.txt](https://github.com/HALFpipe/HALFpipe/files/12965122/err.txt)

**What is the exact command that you used to run `Halfpipe`?**
Please copy it here in full.

**Which settings did you use?**
Please provide the contents of the `spec.json` file from your `Halfpipe` working directory. Note that this files contains all information entered in the user interface. If the error that you are reporting occurred in the user interface, the file may not exist.
[submit.torque.txt](https://github.com/HALFpipe/HALFpipe/files/12965139/submit.torque.txt)

**Comment by HippocampusGirl** [comment]
Hi @ruiyangge

Thanks, I'm glad our tool is of use to you! 

Could you have a look and see if the variable "PBS_ARRAY_INDEX" is indeed the one where your cluster stores the current index of the array job? 

The easiest way to do this is to add "env" as a line to the "submit.torque.sh" script and the look at the output.

**Comment by ruiyangge** [comment]
@HippocampusGirl Thanks Lea for your prompt response. The problem was solved, and yes "PBS_ARRAY_INDEX" is the variable to store the index, however, I submitted the job with "bash" not "qsub" and I did not know it makes a difference. Anyway, thanks a lot to you and we'll disseminate Halfpipe to our colleagues as it's veryuseful.

**Comment by ruiyangge** [comment]
@HippocampusGirl Thanks Lea for your prompt response. The problem was solved, and yes "PBS_ARRAY_INDEX" is the variable to store the index, however, I submitted the job with "bash" not "qsub" and I did not know it makes a difference. Anyway, thanks a lot to you and we'll disseminate Halfpipe to our colleagues as it's veryuseful.
