### ISSUE TITLE
Delete key not working

### ISSUE THREAD

**Issue by elenapozzi** [HALFpipe/HALFpipe#722]
**What happened?**
I downloaded the latest version 1.2.2.post1.dev745+gec7aabd. When I tried to press the 'delete' key to delete characters in the GUI, it didn't work and I was not able to delete characters (see screenshot as example while trying to rename the model). This happened both on the HPC using Singularity and on my local machine using Docker. I didn't have this issue with version 1.2.2.post1.dev724+g9a182ff. 

<img width="449" alt="Screenshot 2024-05-08 at 1 53 11 pm" src="https://github.com/HALFpipe/HALFpipe/assets/28977007/4c25a7de-e1d2-45bf-a3ec-a790d20580e1">

**Is there an error message?**
No

**What is the exact command that you used to run `Halfpipe`?**
singularity run --containall --bind /:/ext halfpipe-latest.sif --only-spec-ui

**Which settings did you use?**
N/A

**Comment by HippocampusGirl** [comment]
I have been able to confirm this issue. I will try to find a fix soon

**Comment by HippocampusGirl** [comment]
Hi everyone,

I would appreciate your help in fixing this issue, because both delete and backspace work fine on my computer. I have written the script below. It will display the character codes of any keys you press while it's running. Please copy/paste it into a new file, save the file as `getch.py` and then run it with `python getch.py`. Please press delete and take a screenshot, and then press backspace and take another screenshot. 

Thanks!

```python
import curses
import curses.ascii

window = curses.initscr()

curses.start_color()
curses.use_default_colors()

curses.raw()
curses.noecho()
window.keypad(True)
window.leaveok(True)

y = 0
while (key := window.getch()) != curses.ascii.ETX:
    window.addstr(y, 0, f"Key pressed: {key}")
    y += 1

    max_y, _ = window.getmaxyx()
    if y == max_y:
        break

    window.noutrefresh()
    curses.doupdate()

window.keypad(False)
curses.noraw()
curses.echo()
curses.endwin()
```

**Comment by lalalavi** [comment]
Hi Elena

`
  def main(stdscr):
      curses.raw()
      curses.noecho()
      stdscr.keypad(True)
  
      while True:
          key = stdscr.getch()
          if key == curses.ascii.ETX:  # Ctrl+C to exit
              break
          stdscr.addstr(0, 0, f"Key pressed: {key} ({curses.keyname(key).decode()})")
          stdscr.clrtoeol()
          stdscr.refresh()

curses.wrapper(main)`

**Comment by lalalavi** [comment]
Hi Elena, can you try running this python script just to confirm what you see on your end? (In your Mac and in your HPC system). You can paste it in as a python file as Lea suggested and run it with `python yourname.py`


```
import curses
import curses.ascii

def main(stdscr):
    curses.raw()
    curses.noecho()
    stdscr.keypad(True)

    while True:
        key = stdscr.getch()
        if key == curses.ascii.ETX:  # Ctrl+C to exit
            break
        stdscr.addstr(0, 0, f"Key pressed: {key} ({curses.keyname(key).decode()})")
        stdscr.clrtoeol()
        stdscr.refresh()

curses.wrapper(main)
```

In my case it shows: 
Key pressed: 263 (KEY_BACKSPACE)

I’ve submitted a pull request to Halfpipe to include handling for KEY_BACKSPACE (263), but I think there might be more key codes for backspace depending on terminal settings or environment variables. This would explain why the error occurs in some systems and not others.

If you can share the output you see on both systems, it will help us make sure we’re covering all possible backspace key codes.

Thanks in advance! :)

**Comment by elenapozzi** [comment]
Hi,

Just to clarify, I created the script on our HPC and ran it - but not inside any container - is that right? On my laptop I only have the delete key - which one is supposed to be the backspace? Attached screenshot when I press delete. The key is 127.

Thanks for your help!

 

> On 13 Nov 2024, at 2:59 am, lalalavi ***@***.***> wrote:
> 
> 
￼
