### ISSUE TITLE
simple update to dependency description: include AFNI in list

### ISSUE THREAD

**Issue by mrneont** [HALFpipe/HALFpipe#748]
Hi-

The main GitHub page of HALFpipe provides a credit list of software dependencies:
> HALFpipe relies on tools from well-established neuroimaging software packages, either directly or through our dependencies, including ANTs, FreeSurfer, FSL and nipype. We strongly urge users to acknowledge these tools when publishing results obtained with HALFpipe.

However, I notice it also uses AFNI in many places, which is not mentioned there.  Therefore, it would be nice the description also included:
[AFNI](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/)

Thanks,
pt

**Comment by HippocampusGirl** [comment]
Hi Paul, That's a good catch, I'm sorry for forgetting to add AFNI. I am out of office until the 15th, but will get on this immediately when I'm back!

**Comment by mrneont** [comment]
Hi, Lea- Much appreciated, and no rush. Thanks!
