### ISSUE TITLE
zran_read returned error

### ISSUE THREAD

**Issue by cchaswell** [HALFpipe/HALFpipe#85]
**What happened?**
When I'm in the Halfpipe interface and load in the site's nifti files, I get this error. 

**Is there an error message?**
[err_tours.txt](https://github.com/HALFpipe/HALFpipe/files/6326025/err_tours.txt)

**What is the exact command that you used to run `Halfpipe`?**
singularity run --cleanenv --bind /:/ext halfpipe_latest.sif --use-cluster
**Which settings did you use?**

Please provide the contents of the `spec.json` file from your `Halfpipe` working directory. Note that this files contains all information entered in the user interface. If the error that you are reporting occurred in the user interface, the file may not exist.
Does not exist yet.

**Comment by HippocampusGirl** [comment]
The error occurs when fmriprep tries to load the header of `/mnt/BIACnfs/duhsnas-pri.dhe.duke.edu/morey_biac/Lab/Tours/rawdata/sub-COPTSDT09/func/sub-COPTSDT09_task-rest_bold.nii.gz` to determine the number of volumes. 
Could you try opening the file to see if it is a valid NIfTI image?

**Comment by HippocampusGirl** [comment]
If it indeed is an invalid NIfTI image, then we may want to add code to HALFpipe to a) show a warning and then b) exclude the file from analysis.

**Comment by cchaswell** [comment]
I do open a few of the niftis and they seem fine in fslview. Is it saying a specific nifti is corrupt, or all of them?

**Comment by HippocampusGirl** [comment]
The error refers to the file I mentioned above, so that would be the one to look at :-)

**Comment by cchaswell** [comment]
I checked all niftis and they look fine. I think I see where the issue is. Can subject names not have an underscore in them? The subjects are labeled like COPTSD_T01.nii.gz. In some of the error log, it is correct. But in the participant list, the underscore is dropped and the program is looking for "COPTSDT01." For this subject set, I do anat/{subject}.nii.gz. It seems like there is an error if an underscore is in the subject variable. I will try it as COPTSD_{subject}.nii.gz but that doesn't always work for other sites.

**Comment by HippocampusGirl** [comment]
I don't think it's about the file names. The error comes from a low-level function for decompressing the `.nii.gz` and loading it into memory. 

I think the next thing to try would be to unzip the input files, i.e. to run something like `for i in *.gz; do gunzip $i; done` in the folder with the image files.

**Comment by HippocampusGirl** [comment]
Ok, I did some more digging. It seems like this is an issue with an older version of `indexed_gzip` (see https://github.com/pauldmccarthy/indexed_gzip/pull/46). The most recent `latest` version has upgraded that library, so it should fix this issue. If you have time, it would be great if you could try again with the new version :-)

**Comment by HippocampusGirl** [comment]
Will close this for now. Please re-open the issue if it turns out that the new release does not solve the issue :-)
